@startuml
package "spaceinvaders" {

    package "ui" {
        [TouchInput]
        package "components"
    }
    
    package "manager" {
        [GraphicsManager] -down-> Graphics
        [ShootManager] -> [GraphicsManager] : use
        [ShootManager] --> Shoot : manages
        [ScoreManager]
    }

    

    package "entity" {
        [Spaceship] -down-> [PlayerSpaceship]
        [Spaceship] -down-> [EnemySpaceship]
        [Invasion] --> [EnemySpaceship] : use
        [Spaceship] ..> TouchInput : use
    }

    package "screens" {
        [GameScreen] --> [TouchInput] : use
        [GameScreen] ---> [Spaceship] : renders
        [GameScreen] ---> [Invasion] : renders
        [GameScreen] --> [ShootManager] : use
        [GameOverScreen]
        [GameWinScreen]
        [MainMenuScreen]
    }

    [SpaceInvaders] -> Game
    [SpaceInvaders] .> [ScoreManager] : creates
    [SpaceInvaders] .> screens : manages


    manager ...> entity : <depends>
    screens ...> components : use
}

@enduml